# Generated by Django 3.2.4 on 2021-10-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostObjects',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='blogImg',
            field=models.ImageField(default='default\x07rian-darvishi-wh-RPfR_3_M-unsplash.jpg', upload_to='images/'),
        ),
    ]
